export const MENU_LINKS = [
  {
    link_name: 'Account Information',
    link: '',
    icon: 'home',
    sub_menu: [],
    id: 'account_information',
  },
  {
    link_name: 'Information',
    link: null,
    icon: 'view_module',
    sub_menu: [
      {
        link_name: 'Contact Information',
        link: '',
        id: 'contact_information',
      },
      {
        link_name: 'General Information',
        link: '',
        id: 'general_information',
      },
      {
        link_name: 'Personal Information',
        link: '',
        id: 'personal_information',
      },
    ],
  },
  {
    link_name: 'Address Information',
    link: '',
    icon: 'view_module',
    sub_menu: [],
    id: 'address_information',
  },
  {
    link_name: 'Employment Information',
    link: '',
    icon: 'view_module',
    sub_menu: [],
    id: 'employment_information',
  },
  {
    link_name: 'Customer Due Diligence',
    link: '',
    icon: 'view_module',
    sub_menu: [],
    id: 'customer_due_diligence',
  },
  {
    link_name: 'ID Information',
    link: '',
    icon: 'view_module',
    sub_menu: [],
    id: 'id_information',
  },
  {
    link_name: 'Financial Information',
    link: '',
    icon: 'view_module',
    sub_menu: [],
    id: 'financial_information',
  },
  {
    link_name: 'Source of Wealth',
    link: '',
    icon: 'view_module',
    sub_menu: [],
    id: 'source_of_wealth',
  },
  {
    link_name: 'Suitability',
    link: '',
    icon: 'view_module',
    sub_menu: [],
    id: 'suitability',
  },
];
